export const actionTypes = {
    USER_LOAD_DATA: 'USER_LOAD_DATA',
    USER_LOAD_DATA_SUCCESS: 'USER_LOAD_DATA_SUCCESS',
    USER_LOAD_DATA_ERROR: 'USER_LOAD_DATA_ERROR',
    USER_SET_LOGIN: 'USER_SET_LOGIN',
    USER_ERROR_LOGIN: 'USER_ERROR_LOGIN',
    USER_LOAD_VERIFY: 'USER_LOAD_VERIFY',
    USER_LOAD_LOGOUT: 'USER_LOAD_LOGOUT',
    USER_SET_LOGOUT: 'USER_SET_LOGOUT',
    USER_UPDATE_LOAD_DATA: 'USER_UPDATE_LOAD_DATA',
    USER_UPDATE_LOAD_DATA_SUCCESS: 'USER_UPDATE_LOAD_DATA_SUCCESS',
    USER_UPDATE_LOAD_DATA_ERROR: 'USER_UPDATE_LOAD_DATA_ERROR',
};
